### ISSUE TITLE
/users endpoint is limited to 1000 usernames

### ISSUE THREAD

**Issue by alsp80** [agiguere/SCPmsPushNotificationREST_API#1]
When sending a push request to the /users endpoint of an app, based on my testing, the limit for number of usernames in such a request is 1.000. If the request contains more usernames, e.g. 1.001 the endpoint will reply with an HTTP 400 response. This is based on testing against CPms running on NEO environment.

I will try with a change to method PUSH_TO_APP_USERS( ) to split into multiple requests per every 1,000 users and might submit a pull request.

**Comment by agiguere** [comment]
ok good catch, let me know if it works and I will merge your PR#
